### ISSUE TITLE
Summon Item Should Only Work in Frost Biome at Night

### ISSUE THREAD

**Issue by alecrm** [SleddGang/Rognir#18]
Currently a player can summon Rognir anywhere in the world. We want to limit this to only being able to summon him in the Frost biome.

**Comment by benjazzy** [comment]
Since Rognir will also spawn in undead vikings during phase two and their ai goes dumb during the day we may want him to only spawn during the night.

**Comment by alecrm** [comment]
Yes, he should only spawn at night

**Comment by benjazzy** [comment]
Finished will pull request #75
