### ISSUE TITLE
Update Boss Fight Music

### ISSUE THREAD

**Issue by alecrm** [SleddGang/Rognir#19]
We want to update the music played when fighting Rognir to address the following points:

- Fill out a wider range of frequencies within the song
- Reflect a pirate/ocean feel to the song to hint at Rognir's lore of being an ancient pirate captain that was frozen to death
- Once Rognir reaches Phase 2, the music should add **minor** tweaks

**Comment by pkingGMU** [comment]
Merged with pull request #94
