### ISSUE TITLE
Update Rognir's Standard Movement AI

### ISSUE THREAD

**Issue by alecrm** [SleddGang/Rognir#22]
Currently Rognir only floats and randomly moves above the player. We want to add a more natural feel to his movements. As a part of this, we need to research into how other bosses (Skeletron, Eye of Cthulu, etc.) move when not attacking.

- When a player is on the ground, Rognir mostly floats above them, maybe occasionally dipping to their sides.
- When a player is in the air, Rognir can be floating anywhere around them..
- Rognir should be staying at random (specifically not constant) distances from the player
- Rognir should not occasionally randomly move onto the player unless attacking them

**Comment by benjazzy** [comment]
Rognir is now slower and no longer moves around randomly.  Now he will chose between floating above the player or to the sides of the player. #32
