### ISSUE TITLE
Update Rognir's Art - Phase 2

### ISSUE THREAD

**Issue by alecrm** [SleddGang/Rognir#24]
We need to add additional art for Rognir's second phase:

- Add a transitional animation for when he converts from Phase 1 to Phase 2
- Create at least two new animations for his second phase (two to make him seem animated)
     - These should include more armor and less ice. Should be more intricate visuals
- New dash animation with his Phase 2 art

**Comment by SaltedHQ** [comment]
Done, good riddens. Closed as of pull request #105
