### ISSUE TITLE
Rognir's Anchor Should Be a Second Entity For His Second Phase

### ISSUE THREAD

**Issue by alecrm** [SleddGang/Rognir#25]
When Rognir reaches his second phase, his anchor should separate from him and become its own entity that also attacks players. The AI should have the anchor constantly spinning (slow-medium speed) and speeding up as it dashes towards a player (then slowing down once passing through or past a player)

**Comment by alecrm** [comment]
Should the anchor do more damage if a player it hits has the chill debuff?

**Comment by benjazzy** [comment]
Rognir's anchor will spawn in during stage two.  It will dash at the player and spin when not dashing until it is facing towards a player where it will dash again.  Currently it also deals extra damage to players that have the chilled debuff active.  The anchor will switch targets every 2 to 4 dashes.  Completed with #42
