### ISSUE TITLE
Increase Frequency of Phase 1 Attacks when Rognir reaches Phase 2

### ISSUE THREAD

**Issue by alecrm** [SleddGang/Rognir#26]
Once Rognir reaches Phase 2, he should:
- dash more often at players
- Shoot out 3 ice spikes instead of just one

**Comment by alecrm** [comment]
Should the Chill debuff last longer during the second phase?

**Comment by benjazzy** [comment]
I think the chill debuff should last longer.  Maybe 5 seconds compared to 2 in phase one.

**Comment by alecrm** [comment]
Another thought I had (and this may already be in the Anchor issue) is that the Anchor deals more damage to Chilled players

**Comment by benjazzy** [comment]
Rognir's attack cooldown is reduced when he enters phase two.  He also shoots out more projectiles and dashes faster.  The chill debuff lasts longer in phase two.  Completed with #39.
