### ISSUE TITLE
Determine Final Stats for Rognir

### ISSUE THREAD

**Issue by alecrm** [SleddGang/Rognir#28]
We need to actually determine final stats for Rognir. This will include play testing (both from the start of a Terraria world as well as just cheating in armor to be roughly where we want to face him).

Do we want any stats (damage?) to increase during Phase 2?

**Comment by alecrm** [comment]
Updated Rognir's hitbox for Stage 2 Merged with Pull Request #61

**Comment by alecrm** [comment]
Updated with pull request #78

**Comment by alecrm** [comment]
Updated with pull request #80
Changed how Rognir's health scales in expert mode with multiple people. It now scales by an additional 35% with each additional person

**Comment by benjazzy** [comment]
Updated will pull request #113 
Rognir will now pause for a quarter of a second between dashes and will now shoot out his shards in a spinning star pattern between stages.

**Comment by alecrm** [comment]
Merged with pull request #132
Increased Rognir's health, defense and dash timer. Reduced spread of ice shards. Increased speed of ice shards. Rognir now shoots 3 ice shards during both stages.
