### ISSUE TITLE
Determine Additional Boss Drops

### ISSUE THREAD

**Issue by alecrm** [SleddGang/Rognir#29]
We need to determine final loot drop for Rognir upon defeating him. Includes:

- Money
- Potions
- Additional items/weapons?
- Ore?

We need to make sure it is relevant to where he is progression-wise in the game

**Comment by alecrm** [comment]
We established additional items as the pickaxe and expert mode only accessory. Need to decide amount for money and potions and whether he drops any ore

**Comment by alecrm** [comment]
- Same potions as Wall of Flesh
- Money drop between Skeletron and Wall of Flesh
- Items/Weapons are done
- No ore

**Comment by Jaredm98** [comment]
Wall of Flesh drops 8 gold coins, which is honestly not much by this point in the game, so I don't see any reason not to have Rognir also drop 8 gold coins

**Comment by alecrm** [comment]
Thanks! How many potions? Like 3-5? I super don't remember

**Comment by alecrm** [comment]
Established 5-15 potions

**Comment by alecrm** [comment]
Merged with Pull Request #112
