### ISSUE TITLE
Determine Final Stats For the Hook Item

### ISSUE THREAD

**Issue by alecrm** [SleddGang/Rognir#38]
We need to determine the following stats for the hook:
- Shoot speed
- Pull speed
- Retreat speed (probably same as pull speed)
- Grapple range
- Hook damage

We also need to confirm the following behavior:
Currently a player can have two hooks active. A third hook can shoot out, but upon collision, the oldest of the two active hooks will be killed. Do we want the third hook to shoot out or do we want it to work like the dual hook?

**Comment by benjazzy** [comment]
Merged with pull request #74.
