### ISSUE TITLE
Update Rognir's Drop Loot

### ISSUE THREAD

**Issue by alecrm** [SleddGang/Rognir#89]
Currently Rognir only drops the Frozen Hook. We have since created two more items -- an Expert mode only drop accessory and a pickaxe (Rognir's Anchor). We want to set Rognir's drop chances as follows:

Normal Mode:
- Always drop ONE of either the Frozen Hook or Rognir's Anchor with a 50% chance for both

Expert Mode:
- Always drop ONE of either the Frozen Hook or Rognir's Anchor with a 50% chance for both
- Always drop the Expert mode only accessory

**Comment by alecrm** [comment]
Added Viking Crown accessory with pull request #97

**Comment by benjazzy** [comment]
Dropping one of either the Frozen Hook or Rognir's Anchor merged with #103.
